# -*- coding: utf-8 -*-
"""LING 270 - CamemBERT Mask Prediction

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TL2QZ86HWzu6zfeOVhw0PDyv9VJB2-ke
"""

# pip installs
!pip install transformers
!pip install torch
!pip install omegaconf
!pip install fairseq
!pip install sentencepiece
!pip install transformers.modeling_camembert
!pip install transformers.tokenization_camembert

# load CamemBERT
import torch
camembert = torch.hub.load('pytorch/fairseq', 'camembert')
camembert.eval()  # disable dropout (or leave in train mode to finetune)

'''
Test Cases:

"elle est très", "intelligente", "intelligent"
"l'information génétique est", "codée", "codé"
"ils deviennent chevaliers du bien", "chargés", "chargé"
"la fille qui achète le chapeau est", "heureuse", " heureux"
"le chien qui mange des pommes est", "petit", "petite"
"la ville qui est petite a été", "construite", "construit"
"le temps de la ville est très", "froid", "froide"
"les droits de les hommes sont très", "grands", "grande"
"la région du pays est", "grande", "grand"
"Le Sahara Occidental a été", "envahi", "envahie"
"Si les 32 États qui n'avaient pas une limite de janvier 2000 avaient", "adopté", "adoptée"
"C'est de cette façon que des conditions radicalement nouvelles ont été", "imposées", "imposés"
"Le premier jour du film était très", "chaud", "chaudes"


'''



test_cases = [
    ("elle est très <mask>", " intelligente", " intelligent"),
    ("l'information génétique est <mask>", " codée", " codé"),
    ("ils deviennent chevaliers du bien <mask>", " chargés", " chargé"),
    ("la fille qui achète le chapeau est <mask>", " heureuse", " heureux"),
    ("le chien qui mange des pommes est <mask>", " petit", " petite"),
    ("la ville qui est petite a été <mask>", " construite", " construit"),
    ("le temps de la ville est très <mask>", " froid", " froide"),
    ("les droits de les hommes sont très <mask>", " grands", " grande"),
    ("la région du pays est <mask>", " grande", " grand"),
    ("Le Sahara Occidental a été <mask>", " envahi", " envahie"),
    ("Si les 32 États qui n'avaient pas une limite de janvier 2000 avaient <mask>", " adopté", " adoptée"),
    ("C'est de cette façon que des conditions radicalement nouvelles ont été <mask>", " imposées", " imposés"),
    ("Le premier jour du film était très <mask>", " chaud", " chaudes")
]

def score_test_cases(test_cases):
  num_correct = 0
  for case in test_cases:
    predictions = camembert.fill_mask(case[0], topk=15000) #change this bit
    correct_pred = 0
    incorrect_pred = 0
    for t in predictions:
      if t[2] == case[1]:
        #print('first')
        correct_pred = t[1]
      if t[2] == case[2]:
        #print('second')
        incorrect_pred = t[1]
    if correct_pred > incorrect_pred:
      num_correct = num_correct + 1
  accuracy = num_correct / len(test_cases)
  print('Number Correct: ' + str(num_correct))
  print('Total Instances: ' + str(len(test_cases)))
  print('Accuracy: ' + str(accuracy))

score_test_cases(test_cases)

